<a href="https://colab.research.google.com/github/Susmithasanapathi/automatic-broccoli/blob/main/python_operators_and_conditional_statements.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# OPERATORS



*operators are used to perform operations on variables

*There are seven types of operators.

1.Arithmatic operators

2.Relational operators or comparison operators

3.Logical operators

4.Identity operators

5.Membership operators

6.Assignment operators

7.Bitwise operators





# ARITHMATIC OPERATORS

  

*   Arithmatic operators is used to perform mathematical operations.

1.addition : It is denoted by '+' operator.

2.Subtraction: It is denoted by '-' operator

3.Multiplication: It is denoted by '*' operator

4.Division:It is denoted by '/' operator

5.Modulus:It is denoted by '%' operator

6.Exponentiation:It is denoted by '**' operator

7.Floor Division:It is denoted by '//' operator




# Example of Arithmatic operator


In [ ]:
a = 10
b = 3

print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a % b)
print(a ** b)
print(a // b)


13
7
30
3.3333333333333335
1
1000
3


# Relational operators or comparison operators

Used to compare two values.

Equal: ==

Not equal: !=

Greater than: >

Less than: <

Greater than or equal to: >=

Less than or equal to: <=


# Example of comparison operator

In [ ]:
a = 10
b = 3

print(a == b)
print(a != b)
print(a > b)
print(a < b)
print(a >= b)
print(a <= b)


False
True
True
False
True
False


#  Logical Operators


Used to combine conditional statements.





and: It is denoted by 'and'

or: It is denoted by 'or'
**bold text**
not:It is denoted by 'not'

In [ ]:
x=5
print(x>3 and x<10)
print(x<3 or x<10)
print(not(x>3 and x<10))

True
True
False


# Identity operators


Identity operators are used to compare the memory locations of two objects.

1.is: Returns True if both variables point to the same object.

2.is not: Returns True if both variables do not point to the same object.


In [ ]:
a = [1, 2, 3]
b = a
c = [1, 2, 3]

print(a is b)
print(a is c)
print(a is not c)

True
False
True


# Membership operator

Membership operators are used to test whether a value or variable is found in a sequence

in: Returns True if the value is found in the sequence.
not in: Returns True if the value is not found in the sequence.

In [ ]:
a = [1, 2, 3, 4, 5]
print(3 in a)
print(6 not in a)

True
True


# Assignment operator

\Used to assign values to variables.

Equals:=

Add and: +=

Subtract and: -=

Multiply and: *=

Divide and: /=

Modulus and: %=

Exponent and: **=

Floor division and: //=

In [ ]:
a = 10

a += 3
print(a)

a -= 3
print(a)

a *= 3
print(a)

a /= 3
print(a)

a %= 3
print(a)

a **= 3
print(a)

a //= 3
print(a)


13
10
30
10.0
1.0
1.0
0.0


# Bitwise operator

Used to perform bit-level operations.

AND: &

OR: |

XOR: ^

NOT: ~

Left Shift: <<

Right Shift: >>

In [ ]:
a = 10
b = 4

print(a & b)
print(a | b)
print(a ^ b)
print(~a)
print(a << 2)
print(a >> 2)


0
14
14
-11
40
2


# Conditional statements

1.if

2.if else

3.if elif else

4.nested if

5.ternary operator or equality operator


# if statement

Used to execute a block of code if a condition is true.


In [ ]:
a = 10

if a > 5:
    print("a is greater than 5")


a is greater than 5


# if else


Used to execute one block of code if a condition is true and another block of code if the condition is false.


In [ ]:
a = 3

if a > 5:
    print("a is greater than 5")
else:
    print("a is not greater than 5")


a is not greater than 5


# if elif else

It is used test multiple conditions.


In [ ]:
a = 5

if a > 5:
    print("a is greater than 5")
elif a == 5:
    print("a is equal to 5")
else:
    print("a is less than 5")


a is equal to 5


# nested if


You can use if statements inside another if statement.

In [ ]:
a = 10
b = 5

if a > 5:
    if b > 3:
        print("a is greater than 5 and b is greater than 3")


a is greater than 5 and b is greater than 3


# **Ternary conditional Operator or equality operator **


Allows you to make a decision in a single line.


In [ ]:
a = 10
result = "a is even" if a % 2 == 0 else "a is odd"
print(result)


a is even


# LOOPS

Loops in Python are fundamental for executing a block of code repeatedly. Here are the two main types of loops: for loops and while loops.


# while loop
While loops execute a block of code as long as a specified condition is true.

In [ ]:
num=int(input())
counter=0
while (counter<3):
  num=num+1
  print(num)
  counter=counter+1


5
6
7
8


# for loop


for loop is used execute over a sequence.


In [ ]:
n=int(input())
for i in range(n):
  print(i)

5
0
1
2
3
4


In [ ]:
word=input()
for eachword in word:
  print(eachword)

python
p
y
t
h
o
n


# lists




*   Lists are used to store multiple items in a single variable.


*   Python used to store collections of data
*   There are three types of built in datatypes


*   tuples
*   set
*   dictionary









# creating list

You can create a list by placing items inside square brackets [], separated by commas.



In [ ]:
# A list of integers
numbers = [1, 2, 3, 4, 5]

# A list of strings
fruits = ["apple", "banana", "cherry"]

# A mixed data type list
mixed = [1, "hello", 3.14, True]


# Accessing Elements

You can access elements in a list using their index, with the first element having an index of 0

In [ ]:
print(numbers[0])  # Outputs: 1
print(fruits[1])   # Outputs: banana


1
banana


# modifying elements

Lists are mutable, so you can change the value of an element

In [ ]:
fruits[1] = "orange"
print(fruits)  # Outputs: ['apple', 'orange', 'cherry']


['apple', 'orange', 'cherry']


# Adding Elements


Append: Adds an element to the end of the list.


Insert: Inserts an element at a specified index.
python









In [ ]:
numbers.append(6)
print(numbers)  # Outputs: [1, 2, 3, 4, 5, 6]

fruits.insert(1, "blueberry")
print(fruits)  # Outputs: ['apple', 'blueberry', 'orange', 'cherry']


[1, 2, 3, 4, 5, 6]
['apple', 'blueberry', 'orange', 'cherry']


# Removing Elements


Remove: Removes the first occurrence of a value.


Pop: Removes an element at a specified index (or the last element if no index is specified).


Del: Deletes an element or slice by index.

In [ ]:
fruits.remove("orange")
print(fruits)  # Outputs: ['apple', 'blueberry', 'cherry']

last_fruit = fruits.pop()
print(last_fruit)  # Outputs: cherry
print(fruits)      # Outputs: ['apple', 'blueberry']

del numbers[2]
print(numbers)  # Outputs: [1, 2, 4, 5, 6]


['apple', 'blueberry', 'cherry']
cherry
['apple', 'blueberry']
[1, 2, 4, 5, 6]


# List Methods

Python lists come with several built-in methods:

sort(): Sorts the list in ascending order.

reverse(): Reverses the order of the list.

index(): Returns the index of the first occurrence of a value.

count(): Counts the number of occurrences of a value



In [ ]:
numbers.sort()
print(numbers)  # Outputs: [1, 2, 4, 5, 6]

numbers.reverse()
print(numbers)  # Outputs: [6, 5, 4, 2, 1]

index_of_4 = numbers.index(4)
print(index_of_4)  # Outputs: 2

count_of_5 = numbers.count(5)
print(count_of_5)  # Outputs: 1


[1, 2, 4, 5, 6]
[6, 5, 4, 2, 1]
2
1


# List Comprehension

List comprehensions provide a concise way to create lists.

In [ ]:
squares = [x**2 for x in range(1, 6)]
print(squares)  # Outputs: [1, 4, 9, 16, 25]


[1, 4, 9, 16, 25]


# Tuples

A tuple is an immutable, ordered collection of items. Once created, the elements of a tuple cannot be changed, added, or removed.


# Creating a Tuple

You can create a tuple by placing items inside parentheses () separated by commas.

In [ ]:
# A tuple of integers
numbers = (1, 2, 3, 4, 5)

# A tuple of strings
fruits = ("apple", "banana", "cherry")

# A mixed data type tuple
mixed = (1, "hello", 3.14, True)

# A single-element tuple (note the comma)
single_element = (42,)


# Tuples Are Immutable

Tuples cannot be changed once created. Attempting to modify, add, or remove elements will result in an error.

In [ ]:
# This will raise an error
numbers[0] = 10  # TypeError: 'tuple' object does not support item assignment


TypeError: 'tuple' object does not support item assignment

# Sets

A set is an unordered collection of unique elements. Sets are mutable, but they do not allow duplicate items.

No duplicate elements.
Elements

are unordered and unindexed.


Supports operations like union, intersection, and difference.


In [ ]:
my_set = {1, 2, 3}
empty_set = set()  # Creates an empty set


In [ ]:
# Union: Elements from both sets
set1 = {1, 2, 3}
set2 = {3, 4, 5}
union_set = set1 | set2
print(union_set)

# Intersection: Elements common to both sets
intersection_set = set1 & set2
print(intersection_set)

# Difference: Elements in set1 but not in set2
difference_set = set1 - set2
print(difference_set)



{1, 2, 3, 4, 5}
{3}
{1, 2}


# Dictionaries

 A dictionary is a collection of key-value pairs.

 A dictionary is a collection which is ordered*, changeable and do not allow duplicates.







In [ ]:
my_dict = {"name": "Alice", "age": 25}
print(my_dict['name'])


Alice


In [ ]:
# A dictionary with integer keys
person = {1: "Alice", 2: "Bob", 3: "Charlie"}

# A dictionary with string keys
student = {"name": "John", "age": 25, "major": "Computer Science"}

# An empty dictionary


In [ ]:
print(student["name"])  # Outputs: John


student["age"] = 26
print(student)  # Outputs: {'name': 'John', 'age': 26, 'major': 'Computer Science'}

# Adding a new key-value pair
student["graduation_year"] = 2024
print(student)  # Outputs: {'name': 'John', 'age': 26, 'major': 'Computer Science', 'graduation_year': 2024}

John
{'name': 'John', 'age': 26, 'major': 'Computer Science'}
{'name': 'John', 'age': 26, 'major': 'Computer Science', 'graduation_year': 2024}


# python libraries




1.Numpy

2.pandas

3.Matplotlib

4.Seaborn

5.Scikit-learn



# *Numpy Library*

numpy is a python library.


Numpy is used for working with arrays.

Numpy stands for "Numerical python".

NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

installation of numpy is "pip install numpy"


# **Why we use numpy**

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called ndarray.

Arrays are very frequently used in data science.

# **Import NumPy**

import numpy or import numpy as np we use both import functions

In [ ]:
import numpy

arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


# **Numpy as np**



NumPy is usually imported under the np alias.

import numpy as np

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


# **Create a NumPy ndarray Object**


We can create a NumPy ndarray object by using the array() function.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

type(): This built-in Python function tells us the type of the object passed to it.

To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:

In [ ]:
import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr)
#using tuple

# Dimensions in Arrays

# 0-D Arrays

0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [ ]:
#Create a 0-D array with value 42
import numpy as np

arr = np.array(42)

print(arr)

# 1-D arrays

An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

These are the most common and basic arrays.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


# 2-D Arrays

An array that has 1-D arrays as its elements is called a 2-D array.

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


## **3-D arrays**

An array that has 2-D arrays (matrices) as its elements is called 3-D array.

In [ ]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


# ***Numpy array indexing ***

# Access Array Elements

Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])
print(arr[1])
print(arr[1]+arr[2])

1
2
5


# **Access 2-D Arrays**
To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.


In [ ]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print( arr[0, 1])

2nd element on 2nd row:  2


In [ ]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print( arr[1, 4])

10


# Access 3-D Arrays

To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

In [ ]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6



# **Negative Indexing**

Use negative indexing to access an array from the end.

In [ ]:
#Print the last element from the 2nd dim:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


# ***NumPy Array Slicing***

# Slicing arrays
Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1









In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [ ]:
#Slice elements from index 4 to the end of the array:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])


[5 6 7]


In [ ]:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])



[1 2 3 4]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])
#
#Slice from the index 3 from the end to index 1 from the end:

[5 6]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])
#step

[2 4]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::1])
#Return every other element from the entire array:

[1 2 3 4 5 6 7]


# Slicing 2-d array


From the second element, slice elements from index 1 to index 4 (not included):

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])


[7 8 9]


# Data Types in NumPy

Below is a list of all data types in NumPy and the characters used to represent them.

i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )

In [ ]:
#Get the data type of an array object:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int64


In [ ]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)
#Get the data type of an array containing strings:

<U6


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)
#Create an array with data type string:

[b'1' b'2' b'3' b'4']
|S1


# NumPy Array Copy vs View

The Difference Between Copy and View
The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.



In [ ]:
#Make a copy, change the original array, and display both arrays:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
#example of view
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


# Shape of an Array

The shape of an array is the number of elements in each dimension.

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)#Print the shape of a 2-D array:

(2, 4)


# NumPy Array Reshaping

Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

#Convert the following 1-D array with 12 elements into a 2-D array.

#The outermost dimension will have 4 arrays, each with 3 elements:



[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# Sorting Arrays

Sorting means putting elements in an ordered sequence.

In [ ]:
import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [ ]:
import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))#Sort the array alphabetically:

['apple' 'banana' 'cherry']


# ***Pandas ***

What is Pandas?

Pandas is a Python library used for working with data sets.

It has functions for analyzing, cleaning, exploring, and manipulating data.

Installation of pandas is import pandas as pd

In [ ]:

import pandas as pd

mydataset = {
  'cars': ["BMW", "Volvo", "Ford"],
  'passings': [3, 7, 2]
}

myvar = pd.DataFrame(mydataset)

print(myvar)

    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2


# **What is a Series?**
A Pandas Series is like a column in a table.

It is a one-dimensional array holding data of any type.

In [ ]:
import pandas as pd

a = [1, 7, 2]

myvar = pd.Series(a)

print(myvar)

0    1
1    7
2    2
dtype: int64


# Labels

If nothing else is specified, the values are labeled with their index number. First value has index 0, second value has index 1 etc.

This label can be used to access a specified value.

In [ ]:
print(myvar[0])#Return the first value of the Series:

1


# create Labels

With the index argument, you can name your own labels.


In [ ]:
#Create your own labels:

import pandas as pd

a = [1, 7, 2]

myvar = pd.Series(a, index = ["x", "y", "z"])

print(myvar)
print(myvar["y"])

x    1
y    7
z    2
dtype: int64
7


# Key/Value Objects as Series

You can also use a key/value object, like a dictionary, when creating a Series.

In [ ]:
#create a simple Pandas Series from a dictionary:

import pandas as pd

calories = {"day1": 420, "day2": 380, "day3": 390}

myvar = pd.Series(calories)

print(myvar)

day1    420
day2    380
day3    390
dtype: int64


In [ ]:
#Create a Series using only data from "day1" and "day2":

import pandas as pd

calories = {"day1": 420, "day2": 380, "day3": 390}

myvar = pd.Series(calories, index = ["day1", "day2"])

print(myvar)

day1    420
day2    380
dtype: int64


# **DataFrames**

Data sets in Pandas are usually multi-dimensional tables, called DataFrames.

Series is like a column, a DataFrame is the whole table.

In [ ]:
#Create a DataFrame from two Series:

import pandas as pd

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

myvar = pd.DataFrame(data)

print(myvar)

   calories  duration
0       420        50
1       380        40
2       390        45


# What is a DataFrame?
A Pandas DataFrame is a 2 dimensional data structure, like a 2 dimensional array, or a table with rows and columns.

In [ ]:





#Create a simple Pandas DataFrame:

import pandas as pd

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

#load data into a DataFrame object:
df = pd.DataFrame(data)

print(df)
print(df.loc[0])

   calories  duration
0       420        50
1       380        40
2       390        45
calories    420
duration     50
Name: 0, dtype: int64


**Named Indexes**
With the index argument, you can name your own indexes.

In [ ]:
Add a list of names to give each row a name:

import pandas as pd

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

df = pd.DataFrame(data, index = ["day1", "day2", "day3"])

print(df)
print(df.loc["day2"])

# *Load Files Into a DataFrame*
If your data sets are stored in a file, Pandas can load them into a DataFrame.

In [ ]:
import pandas as pd

df = pd.read_csv('data.csv')

print(df)

In [ ]:
#check the number of maximum returned rows:

import pandas as pd

print(pd.options.display.max_rows)


60


# Pandas - Analyzing DataFrames
# Viewing the Data
One of the most used method for getting a quick overview of the DataFrame, is the head() method.

The head() method returns the headers and a specified number of rows, starting from the top.

In [ ]:
#Get a quick overview by printing the first 10 rows of the DataFrame:

import pandas as pd

df = pd.read_csv('data.csv')

print(df.head(10))

There is also a tail() method for viewing the last rows of the DataFrame.

The tail() method returns the headers and a specified number of rows, starting from the bottom.

In [ ]:
print(df.tail())

# **Info About the Data**
The DataFrames object has a method called info(), that gives you more information about the data set.



In [ ]:

#Print information about the data:

print(df.info())

# Data Cleaning

Data cleaning means fixing bad data in your data set.

Bad data could be:

Empty cells
Data in wrong format
Wrong data
Duplicates
In this tutorial you will learn how to deal with all of them.

